development:
  host: localhost:8080
  email: koen@shootmyride.nl
  password: 3Baco900
staging:
  host: staging.example.com
  email: john@doe.net
  password: easyone
production:
  host: www.example.com
  email: john@doe.net
  password: easyone
