development:
  host: localhost:8080
  email: test@test.com
  password: test
staging:
  host: staging.shootmyride.nl
  email: test@test.com
  password: test
production:
  host: www.shootmyride.nl
  email: test@test.com
  password: test
