development:
  host: localhost:8080
  email: koen@shootmyride.nl
  password: 3Baco900
staging:
  host: staging.shootmyride.nl
  email: koen@shootmyride.nl
  password: 3Baco900
production:
  host: www.shootmyride.nl
  email: koen@shootmyride.nl
  password: 3Baco900
