site:
  name: "Shoot my Ride"

  locales: [nl]

  seo_title: "Shoot my Ride"
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
    - "index":
        title: "Home"
        published: true
        listed: true
    - "over-ons":
        title: "Over ons"
        published: true
        listed: true
    - "onze-diensten":
        title: "Onze diensten"
        published: true
        listed: true
    - "portfolio":
        title: "Portfolio"
        published: true
        listed: true
    - "portfolio/detail":
        title: "Portfolio detail"
        published: true
        listed: false
        templatized: true
        model: photoshoots
    - "contact":
        title: "Contact"
        published: true
        listed: true
    - "algemene-voorwaarden":
        title: "Algemene voorwaarden"
        published: true
        listed: false
    - "404":
        title: "Pagina niet gevonden"